name: Build WPF Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ./src/AimbotSimulator.csproj

    - name: Build project
      run: dotnet build ./src/AimbotSimulator.csproj --configuration Release --no-restore

    - name: Optional — Publish
      run: dotnet publish ./src/AimbotSimulator.csproj -c Release -o ./publish
